### ISSUE TITLE
Clean up "notation search" dropdown

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/cantus#100]
Just got this image from Inga asking why something wasn't working...

![image](https://cloud.githubusercontent.com/assets/3514397/4943019/b2fc943e-65f0-11e4-990e-8dd5e48b4e72.png)

Two suggestions off this:

1) Switch "PNames" to "Pitches"
2) If pitch isn't used for a specific manuscript (the two St. Gall ones), disable it

**Comment by AFFogarty** [comment]
What search field types are available are now determined by what plugins are activated on the particular manuscript.

For example, activating the "Neume Search" plugin makes the neume search box appear, etc.
