### ISSUE TITLE
Arrow keys in search field are still focused on the diva viewer

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#101]
If you put text in the search field but then try to use your arrow keys to move your cursor, it will not move and the diva view will move instead.

Observed in Safari; not tested in others.

**Comment by ahwitz** [comment]
@wabain - is this still a problem? There may be a fix to this problem in https://github.com/DDMAL/diva.js/commit/61358803f016bbc8e47d36894f0a2f17665d8b0a

**Comment by wabain** [comment]
Pretty confident this is fixed. I haven't encountered it on develop,
although I don't think I've made a focused efforts to produce it. I can
reopen this and DDMAL/diva.js#237 if I find some action that breaks it.

**Comment by ahwitz** [comment]
Do you still have enableKeyScroll/enableSpaceScroll = false?

**Comment by ahwitz** [comment]
Just confirmed it was fixed on the ddmal.github.io/diva.js "Try It" pages. Cool.
