### ISSUE TITLE
Searching with or without significative letters

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/cantus#103]
We've been classifying all the significative letters, but these are extra-musical content. (Think dynamics or articulations instead of the notes themselves on a modern score.) Someone should probably be discussing with Inga and Kate how they envision the need to search these letters, but I would envision the need to be able to search n-grams with the significative letter AND without them. We may also need to discuss, eventually, how (or if) each letter is connected to specific neumes or neume parts and how to encode this in MEI.

**Comment by AFFogarty** [comment]
Tim, do you have any examples of what significative letters are and/or what they look like?
