### ISSUE TITLE
Diva page disappears before leaving visible viewport

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#105]
As you scroll up in a diva document the previous page image is not supposed to be removed from view until it has left the viewport. However, in both cantus and dev-cantus the bottom visible page disappears while still visible. 

https://dl.dropboxusercontent.com/u/1996023/cantus-page-disappears.mov

**Comment by AFFogarty** [comment]
Evan and I were investigating this back during the summer.  It has to do with Diva's internal size calculations being overridden if you manually adjust the size of `diva-outer`.

If Diva had a public function that allowed us to manually re-invoke the internal size calculations then this would probably solve the issue.  I can look into how this could be implemented.

**Comment by magoni** [comment]
This is still happening, not sure why...

**Comment by wabain** [comment]
Additional screenshot from dev-cantus:

![screen shot 2015-05-25 at 10 21 05](https://cloud.githubusercontent.com/assets/7651435/7798439/df72b600-02c7-11e5-9c2c-fedb59d192a5.png)

**Comment by ahwitz** [comment]
What commit of Diva is this on?

**Comment by wabain** [comment]
It was updated the latest version of Diva on March 5 (Cantus commit 1c4d569).

**Comment by ahwitz** [comment]
Is https://github.com/DDMAL/cantus/commit/8274ec8603f36ab6d9813b8fb3b7aeaa86c2b70a#diff-5425f048401a9be39373bb088b2966cdR94 still getting called, and called at the correct time?

**Comment by wabain** [comment]
It doesn't seem to be getting called on page resize. Is that when it should be called?

**Comment by wabain** [comment]
Okay, it works on <http://cantus.simssa.ca> after I manually resize the page, but not on initial load. It doesn't work at all on dev-cantus. It should be pretty easy for me to track down the regression.

**Comment by magoni** [comment]
Cool. When you're calling it on initial load just make sure it's happening after height resizing happens to Diva's containing `<div>`.

**Comment by ahwitz** [comment]
What Evan said, and this refs https://github.com/DDMAL/diva.js/issues/235 - basically, just publish that event if you change the panel size for any reason that's not resizing the window.

**Comment by wabain** [comment]
Now that DDMAL/diva.js#260 is fixed it should be possible to close this once Cantus starts using Diva 4.0.

**Comment by wabain** [comment]
:tada: :balloon:
