### ISSUE TITLE
Make some manuscripts private

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#108]
Certain manuscripts should not be accessible to the general public.

**Comment by fujinaga** [comment]
Which manuscripts are these? 
I'd like to put only public-domain manuscripts on the Cantus site.

**Comment by ahankinson** [comment]
I wanted this so that we can wait until we have everything in place for a manuscript before we make it available on the main site.

**Comment by fujinaga** [comment]
Got it. No problem.

**Comment by wabain** [comment]
Status update on this: The `public` field on the manuscript model is used to filter what manuscripts are visible on the Manuscripts page, but other manuscripts are still accessible if their URL is entered directly.

**Comment by napulen** [comment]
This is what the staging environment is for. 

We may keep the `public` attribute to preserve the current functionality of the website in the near future, but eventually, maybe this should all be handled by having a production and staging instances of the website.
