### ISSUE TITLE
Solr sorts Chant folio in a strange order

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#116]
It looks as though Solr sorts the folios in a peculiar manner.  It sort of looks like it's doing lexicographic ordering from the right:

![Search result](http://i.imgur.com/vf68Ymh.png)

**Comment by wabain** [comment]
This was resolved via #145, if not earlier.

**Comment by wabain** [comment]
Reopening this; Solr is still doing this, although now Backbone masks it somewhat.

**Comment by wabain** [comment]
http://stackoverflow.com/questions/7991885/solr-wrong-sort-text-fields
