### ISSUE TITLE
Improve ChangeChant event parameter

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#125]
Right now, the ChangeChant event parameter is just a single integer representing the index of the chant that we are switching to.

I would like to change the parameter to be an object that looks like this:

```
{
    chantIndex: int,
    isFirstLoad: bool
}
```

By including the `isFirstLoad` parameter, event listeners can react differently depending on whether or not this is the first time that the event has been called for a particular folio.  This change would give me a vector to finally approach fixing #72 (which is caused by events firing immediately after the page first loads) and also help for implementing #119.

**Comment by wabain** [comment]
I've implemented a tweaked version of this where the object is the second event argument; see commits 4e48878 and bd5ac9b for details.
