### ISSUE TITLE
Page navigation buttons look weird in Chrome

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#130]
The diva control bar has different sizes in Chrome than in Safari.

**Comment by AFFogarty** [comment]
Do you have a screenshot?  It looks normal to me.

**Comment by ahankinson** [comment]
Ok, I guess it looks the same but I think it still looks a bit sloppy.

![cantus-screenshot](https://cloud.githubusercontent.com/assets/163183/6760341/96524f64-cf3f-11e4-8506-a0d3d4e00b44.png)

**Comment by ahankinson** [comment]
The 'go' button is of a different height than the other buttons, the text input field is weird, and the 'page 1 of xxxx' is not aligned with the tops of the other buttons.

**Comment by wabain** [comment]
This seems to be an effect of #175. The sizes are wrong because the styling isn't being applied.
