### ISSUE TITLE
Number of results in text search

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#135]
> When doing a text search we'd like to see the number of results (already appears when doing manuscript search).

Refs #132

**Comment by AFFogarty** [comment]
Alright, I have this working quite well.  Should I close the issue?

![screen shot 2015-03-16 at 9 09 48 am](https://cloud.githubusercontent.com/assets/2154530/6666609/5722d6a0-cbbc-11e4-88d4-dc234a90aeb1.png)

**Comment by ahwitz** [comment]
One small hesitation: I'm used to seeing "1 to 10 of 46" or something
similar at the bottom if it's paginated. Doesn't mean it's better than what
you did or necessary, but food for thought.

**Comment by AFFogarty** [comment]
Well, I designed it to look like the mockup that Barbara Swanson made:

![image](https://cloud.githubusercontent.com/assets/2154530/6666956/0aa2dc1e-cbbf-11e4-8ba7-b3f87db9301c.png)

**Comment by ahwitz** [comment]
By all means trust her over me. Didn't see the mockup.

**Comment by AFFogarty** [comment]
Ok I'm going to close this because it looks exactly like the mockup.
