### ISSUE TITLE
Mode displayed as part of the meta-data from Cantus.

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#138]
> We would like to see the mode displayed as part of the meta-data from Cantus.

Refs #132

**Comment by ahankinson** [comment]
Clarification: The 'mode' should be displayed in the search results, esp. with the Volpiano and OMR search results.

**Comment by AFFogarty** [comment]
So in order to accomplish for OMR results we will have to re-structure the way that OMR results are displayed.  I'm going to close this issue and open a new one for investigating how to display the OMR results.

**Comment by AFFogarty** [comment]
Refs #152
