### ISSUE TITLE
Heading for "text" search should be changed

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#140]
> Heading for "text" search should be changed to something else since it includes a Volpiano search. Perhaps "Index" search? Or should Volpiano be moved under "Notation search?"

Refs #132

**Comment by wabain** [comment]
Seems to me that grouping Volpiano with the neumes and pitches makes sense. It would be nice to have a way to differentiate PNames and Volpiano clearly too.

**Comment by wabain** [comment]
This has been changed to "Chant search", which is accurate.
