### ISSUE TITLE
New layout for Text search/Volpiano

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#142]
> For the Text search/Volpiano,we'd like the results page to look more like this, with the chant name running across the top and the actual chant below, so that the chant doesn't get squished onto multiples lines at the side of the field. Can you also add a Query field that preserves the query as users click on individual results. And, we'd like the number of results to display.

![image](https://cloud.githubusercontent.com/assets/2154530/6626045/68461806-c8ca-11e4-95f3-4136bdea473f.png)

Refs #132

**Comment by wabain** [comment]
This was mostly implemented by @AFFogarty. The only thing here which hasn't been completed is the query being preserved as users click on individual results, which pertains to issue #136.
