### ISSUE TITLE
"Next Page" or arrow up and down

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#143]
> Need a "Next Page" or arrow up and down to navigate folio by folio.

Refs #132

**Comment by AFFogarty** [comment]
This is what the buttons currently look like:

![image](https://cloud.githubusercontent.com/assets/2154530/6642296/011300d0-c97a-11e4-926c-32d9ae9e553f.png)

**Comment by AFFogarty** [comment]
Right now it's using the default Bootstrap vertical spacing for a "pager" widget.  I plan to reduce the vertical spacing.

**Comment by ahankinson** [comment]
I think it looks fine as it is. It's there an particular issue with the current vertical spacing?

**Comment by fujinaga** [comment]
Can we use icons where possible, i.e., add arrows?
Makes things more international...

Ich

**Comment by ahankinson** [comment]
We can add arrow icons from the bootstrap set, but I think we should still keep the text labels to make it obvious.

**Comment by fujinaga** [comment]
That'd be fine,

Ich

**Comment by AFFogarty** [comment]
This is what I made them look like:

![screen shot 2015-03-20 at 9 41 40 am](https://cloud.githubusercontent.com/assets/2154530/6752489/5ced2b7c-cee5-11e4-9f2b-3fd4e58ebecb.png)

**Comment by fujinaga** [comment]
Very nice!

Ich

**Comment by AFFogarty** [comment]
Thanks!  I'll go ahead and close this issue now.

**Comment by ahankinson** [comment]
Hm. I find it a bit strange that left/right arrows scroll the page up/down.

Can't you use the up/down arrows instead?
