### ISSUE TITLE
Enter the actual folio number to go to page

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#144]
> We need to be able to enter the actual folio number. For St. Gall 390, the page numbering at source needs to be adjusted, because at present, we need to add 3 in the page number field to get the correct folio to display. Perhaps the correct pagination can be pulled from ecodices? See also the same issue in Salzinnes, below:

![image](https://cloud.githubusercontent.com/assets/2154530/6626068/a004b8e2-c8ca-11e4-8a53-bdcc285ab4cf.png)
![image](https://cloud.githubusercontent.com/assets/2154530/6626076/a3961b9a-c8ca-11e4-8575-037e28c54c9c.png)

Refs #132

**Comment by ahankinson** [comment]
Some MSS are foliated, some are paginated. Folios have r/v in the name, pages are just numbers

Do a search field for goto folio / page.
