### ISSUE TITLE
Order results by criteria

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#145]
> We need Results to display in order by folio, not randomly (as in Ex. 1 below). Ideally, we want to sort results by criteria like folio #, feast, mode... 

Ex 1:

![image](https://cloud.githubusercontent.com/assets/2154530/6626121/efeee94a-c8ca-11e4-8f5a-4a2de2528324.png)

Ex 2:

![image](https://cloud.githubusercontent.com/assets/2154530/6626112/dfc1cd12-c8ca-11e4-8b6a-3b7c78bd14b3.png)

Refs #132

**Comment by AFFogarty** [comment]
Ok, I've been thinking about how sorting would work with regards to pagination.

Suppose I have sorted my results by folio and I am on search result page 6.  I click on the arrow to sort by mode.  Do I get taken to search result page 1?

**Comment by ahankinson** [comment]
Can we auto-load and get rid of the pagination?

See: http://salzinnes.simssa.ca. Search for 'domine' and then scroll down. 

The results load as you scroll. Then sorting will be very easy.

**Comment by wabain** [comment]
I have a first-pass implementation of this done. At the moment, users can only sort by the four fields which appear in the result table, but extending that to handle feast, office, etc. might be a matter of making it possible to customize the table fields, which would be a separate issue. (And the "type" field should probably be removed; it's pretty useless.)

@ahankinson thoughts?

![screen shot 2015-06-12 at 12 30 17 pm](https://cloud.githubusercontent.com/assets/7651435/8137160/5045e564-110f-11e5-8412-ba872d0516ce.png)

**Comment by ahankinson** [comment]
I'm not sure about making it customizable, but perhaps we can start thinking about an extended search view or something. 

But yes, the `type` field is pretty useless. Perhaps Office?
