### ISSUE TITLE
Search Query and Results heading to stay stable on the page

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#146]
> We need the Search Query and the Results heading to stay stable on the page as we scroll through the results. At present, these disappear as we scroll.

![image](https://cloud.githubusercontent.com/assets/2154530/6626145/1437218c-c8cb-11e4-942c-00710dff767f.png)

Refs #132

**Comment by wabain** [comment]
Most of this has been completed. What's left is making the table headers sticky instead of having them scroll, which will take some JS magic.

**Comment by jeromepl** [comment]
I have worked on a CSS method for having fixed table headers. It currently works but has a lot of inconvenients:

- Each column needs to have a fixed percent width
- If a word does not fit in the column it overflows on the following column or, if on the last column, leads the table to have a horizontal scrollbar
- Seems to be much slower than previous versions (Browser takes time to recalculate all rows' height)
- There always needs to be a scrollbar for the headers to be aligned

I think working on a JS fix for this would work better. There are a ton of jQuery plugins that do this, such as [FixedHeaderTable](http://www.fixedheadertable.com/) and [floatThead](http://mkoryak.github.io/floatThead/). None of them seems to have an example for a resizable table though.
