### ISSUE TITLE
Make the MS and manuscript info panels resizable

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#148]
> Can the vertical line dividing the manuscript on the left and the search area on the right be a "sliding" line that moves left or right to adjust the size of either the MS display or the results display? This would be another solution to increase the space for results. 

Refs #132

**Comment by ahankinson** [comment]
This could also be just 'hiding' either the MS view or the right panel.

**Comment by ahankinson** [comment]
I'm going to move this one up the priority list.

**Comment by wabain** [comment]
Is hiding the MS view/info panel still good or does it need to be a more granular resizing?

**Comment by ahankinson** [comment]
Granular resizing (click and drag the separator) would be great, but I suspect it will be a bit crazy for Diva to keep track of it. I think hiding would be fine for now.
