### ISSUE TITLE
Moving manuscript name to top menu

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#149]
Right now, the top menu (the long grey bar that runs along the top of the page) is mostly an empty waste of space.  In addition, the manuscript title takes up a lot of vertical space in the right column:

![image](https://cloud.githubusercontent.com/assets/2154530/6628331/f2291cfc-c8da-11e4-991e-f10dc6f8914f.png)

We can be much more economical with screen space by moving the title of the manuscript to the empty space in the top menu:

![image](https://cloud.githubusercontent.com/assets/2154530/6628334/fbbe297e-c8da-11e4-9b63-539760c9f957.png)

**Comment by ahankinson** [comment]
The tabs look a little funny with this change. Is there a better interface to replace them?

Also how does this look with a long title (like the Salzinnes?) 

You should probably auto-truncate if it's in danger of colliding with the buttons on the right, OR we can move those buttons somewhere else -- perhaps a global drop-down menu to the left of 'Cantus Ultimus'?

**Comment by ahankinson** [comment]
@wabain what do you think? If we go with [provenance], [siglum]?
