### ISSUE TITLE
504 Gateway Time Out on Dev Cantus

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#150]
I'm getting Time Out whenever I try to search on dev-cantus.  This is not happening with production Cantus.

Example: http://dev-cantus.simssa.ca/search/?q=dom%20%20AND%20manuscript:%22CDN-Hsmu%20M2149.L4%22&sort=folio%20asc

**Comment by AFFogarty** [comment]
Restarting Tomcat did not fix this.

**Comment by AFFogarty** [comment]
Ok, this is definitely a Solr-related problem.  When I rebuild Solr for Dev-Cantus the issue is fixed for Dev-Cantus but the same issue suddenly appears on Cantus.  When I rebuild Solr for Cantus then the issue appears on Dev-Cantus.

**Comment by ahankinson** [comment]
Did you change the data-dir?

**Comment by ahwitz** [comment]
I don't know if this is related, but I was trying to look up something about the Salzinnes and realized that all the manuscript IDs are one greater in dev-cantus than in cantus.

**Comment by ahankinson** [comment]
Has this been fixed? It should be the first priority to make sure this works correctly.

**Comment by ahankinson** [comment]
Seems to be fixed now.
