### ISSUE TITLE
Displaying OMR Search Results

### ISSUE THREAD

**Issue by AFFogarty** [DDMAL/cantus#152]
If we want to display OMR metadata in search results then we need to change the GUI.

How should the interface look?

I think that the results should be a table like the chant search result GUI.  When the user clicks on a result in the table, that result row gets highlighted and Diva scrolls to the relevant visual highlight.

**Comment by wabain** [comment]
Done in 7b879c3700d5fc8a7474eaf8d8d079c741953c24.
