### ISSUE TITLE
Switch to HTTPS on the server

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#166]
We should start running HTTPS on the server. We have a certificate, we just need to start using it.

**Comment by ahwitz** [comment]
should this apply to everything on the server as well or just (cantus|dev-cantus).simssa.ca/* ?

and if it's everything, is this going to affect IIP negatively?

**Comment by ahankinson** [comment]
We're running IIP over HTTPS on images.rasi.mcgill.ca, with no negative impact. We had a problem with the certificate chain but @Alistair-Russell and I fixed this last night.

https://images.rasi.mcgill.ca/fcgi-bin/iipsrv.fcgi?FIF=/data7/srv/images/Abd_hamid_mawlawi_398/Abd_hamid_mawlawi_398_0000.jp2&JTL=3,0

**Comment by ahwitz** [comment]
just mentioning @magoni in this so he knows what's going on as well. I think the rest of the stuff running on there is either mine or fogarty's.

would it also be worth it to have everything on http automatically redirect to https?

**Comment by ahankinson** [comment]
fwiw our NginX SSL configuration on this machine looks like this:

```
ssl_ciphers ECDHE-RSA-AES256-SHA384:AES256-SHA256:RC4:HIGH:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!AESGCM;
ssl_session_timeout 5m;
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_certificate /etc/nginx/ssl/$CERTFILE.crt;
ssl_certificate_key /etc/nginx/ssl/$KEYFILE.key;
ssl_ecdh_curve secp521r1;
```

**Comment by ahankinson** [comment]
Yes, I think we should automatically redirect to HTTPS. I usually do that with a new server configuration that sends out a 301 and redirects:

```
server {
    listen 132.216.29.167:80;
    server_name images.rasi.mcgill.ca;
    return 301 https://$server_name$request_uri;
}
```

**Comment by ahwitz** [comment]
:+1:

**Comment by ahankinson** [comment]
We should switch the dev server to use 'Let's Encrypt' https://letsencrypt.readthedocs.org

**Comment by jeromepl** [comment]
The router set up by @lexpar on Compute Canada has been set up to use and SSL connection using a certificate generated by let's encrypt.

**Comment by ahankinson** [comment]
Going to re-open until you've answered this one, just so it doesn't get lost: Did you set up the cron job to automatically renew the certificate?

**Comment by lexpar** [comment]
Yes I did.

**Comment by ahankinson** [comment]
Perfetto!
