### ISSUE TITLE
Use Diva pagealias plugin to remap pages

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/cantus#173]
This specifically applies to St. Gall 390 and to the Salzinnes, but ideally we want the filenames to line up with the page numbers displayed in the "Page ___ of XXX" 

I wrote the documentation for that plugin, so let me know if anything's not clear.

**Comment by ahwitz** [comment]
:+1: everything work smoothly?

**Comment by wabain** [comment]
Yup! But I'm going to open a feature request on Diva for hooks to make it easy to integrate the "go to page" feature.
