### ISSUE TITLE
Move MEI for St. Gall 391 back onto the webserver

### ISSUE THREAD

**Issue by ahwitz** [DDMAL/cantus#174]
It should be somewhere on Gershwin.  

edit: for clarity, "move" here means 'copy'

**Comment by wabain** [comment]
So it used to be on the server but was deleted?

**Comment by ahwitz** [comment]
I think I just ran "touch" on those files for testing purposes, then later saw that the files existed and didn't look at their sizes.

**Comment by wabain** [comment]
Done!
