### ISSUE TITLE
Salzinnes folio 198r is indexed in the Django and Solr databases as 197w

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#180]
This is why searches for musical data in that folio fails. The folio still displays correctly because because the Diva/IIP Image server name is correct.

Refs #137

**Comment by ahankinson** [comment]
What's the status of this one?

**Comment by wabain** [comment]
The updated CANTUS chant info has this fixed and they're showing up on Solr. The chants still aren't showing up on dev-cantus though. I think that might be a problem with the import script.

**Comment by ahankinson** [comment]
OK, thanks!

**Comment by wabain** [comment]
Fixed it manually, just need to update the scripts.

**Comment by ahankinson** [comment]
Can this one be closed now?

**Comment by wabain** [comment]
Yup!

**Comment by ahankinson** [comment]
Awesomesauce.

:+1:
