### ISSUE TITLE
Auto-load search results instead of paginating

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#182]
Remove the pagination in the UI and have results load in one list off of multiple Solr requests (at least two requests: one for the first ten so that the above-the-fold content loads quickly, and then another for the rest).

Refs #145

**Comment by ahankinson** [comment]
For reference, the original Salzinnes application is here:

https://github.com/DDMAL/salzinnes-original

Specifically:

https://github.com/DDMAL/salzinnes-original/blob/master/static/js/diva.js#L1399
