### ISSUE TITLE
Use batch operations to enter data in the database

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#184]
Right now we open a cursor for each new entry in the import scripts. This makes syncing with solr automatic, because it's done by the post_save receiver, but it's really slow. Django provides a `bulk_create` function, but it doesn't fire the post_save signals, so we would need to update Solr separately (which we could also do in batch).

<https://docs.djangoproject.com/en/1.7/ref/models/querysets/#bulk-create>

**Comment by ahankinson** [comment]
I think this is a good idea. Go ahead and implement it, and we can manually update Solr after update.

**Comment by wabain** [comment]
Closing this; I think I've done about as much as possible on this front for the moment.
