### ISSUE TITLE
Add "Activities" tab

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/cantus#186]
Containing publications, presentations, and workshops

**Comment by wabain** [comment]
Is this tab per-manuscript or in the navbar beside "Manuscripts" and "Search"?

**Comment by ahankinson** [comment]
@vigliensoni Can you file this as a pull request with your changes to the app? This way @wabain can review and merge them.

**Comment by vigliensoni** [comment]
@wabain I'm working in the static website, which will add a couple of tabs. I'll file the pull request once it's ready.

**Comment by ahankinson** [comment]
Should Activities get lumped into the SIMSSA webpage and not this one? @fujinaga, should we have a separate page on simssa.ca for just CU activities?

**Comment by fujinaga** [comment]
Good question. I've wondered about that too. Let's leave it as is now and we can ask at MedRen.

**Comment by napulen** [comment]
`Activities` has been there for a while. Assuming it will keep that way.
