### ISSUE TITLE
Line endings are not preserved in manuscript description field

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#191]
In the Manuscript Details -> Description field, the line endings are not present. They are, however, stored in the field visible in the admin interface.

Somewhere along the way (perhaps Django REST Framework serialization?) the linebreaks are being stripped out of the description field.

**Comment by wabain** [comment]
Right, I'd forgotten about this. It's just HTML; if I put it in a `pre` element they'll be preserved.

**Comment by ahankinson** [comment]
Hm, but that will then render it in a monospaced font. 

I'm wondering if we shouldn't move Manuscript Details somewhere else... 

It would free up some badly needed space on the side bar, which right now seems to focus primarily on search functions.

What about a little information icon (i inside a circle) in the title field, and clicking on it will display a modal dropdown with the information about the manuscript.

**Comment by wabain** [comment]
Actually styling it is easy:

![screen shot 2015-06-15 at 5 38 12 pm](https://cloud.githubusercontent.com/assets/7651435/8171380/85525a58-1385-11e5-8a7c-49718b4577da.png)

Moving the info might be a good idea though.

**Comment by fujinaga** [comment]
> On Jun 15, 2015, at 5:23 PM, Andrew Hankinson <notifications@github.com> wrote:
> 
> Hm, but that will then render it in a monospaced font.
> 
> I'm wondering if we shouldn't move Manuscript Details somewhere else…
> 
Yes! 
Why not just click on the name of the manuscript to show the details.

Ich
