### ISSUE TITLE
Search box is in Search this Manuscript is not cleared 

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/cantus#192]
Search box in the Search this Manuscript is not cleared when you change from one field to another, e.g.,  from Mode to Feast.

**Comment by wabain** [comment]
Should it always be cleared? I was thinking that it was better to maintain it, in case someone accidentally selected the wrong field and then switched. Maybe it should only be cleared when going to or from Mode, since that has a different input box?

**Comment by fujinaga** [comment]
> On Jun 15, 2015, at 5:43 PM, William Bain <notifications@github.com> wrote:
> 
> Should it always be cleared? I was thinking that it was better to maintain it, in case someone accidentally selected the wrong field and then switched. Maybe it should only be cleared when going to or from Mode, since that has a different input box?
> 
> —
> 
But each field has its own terms.
It should be kept if the user moves the field selector but puts it back to the original field?
