### ISSUE TITLE
Move manuscript description out of the sidebar

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#194]
> I'm wondering if we shouldn't move Manuscript Details somewhere else...
> 
> It would free up some badly needed space on the side bar, which right now seems to focus primarily on search functions.

Also:

> Just click on the name of the manuscript to show the details.

**Comment by wabain** [comment]
@fujinaga @ahankinson 

How do we make it obvious it's a link?

**Comment by fujinaga** [comment]
Change the icon when you mouse over?

Ich
