### ISSUE TITLE
Not always reloading the Manuscripts page

### ISSUE THREAD

**Issue by fujinaga** [DDMAL/cantus#200]
With Safari on my iPhone 6, if you reload the Manuscripts page, sometimes the "Future Manuscripts" section doesn't show up.  No such issues with Chrome.
![img_6516](https://cloud.githubusercontent.com/assets/1031785/8221997/b696d526-1533-11e5-8fd0-447d3e3d5e57.png)

**Comment by wabain** [comment]
Confirmed fixed by ce77b6be29f6eb89467f77b43b91527ab849ddbd.
