### ISSUE TITLE
Change text input font to Volpiano for volpiano search

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#201]
When entering a search for volpiano it would be a good idea to change the font (and possibly the size) of the search box so that it looks like the user is entering volpiano notation, instead of characters.

**Comment by wabain** [comment]
This would be cool. Should the input font itself change, or should the text
appear below as you type?

**Comment by ahankinson** [comment]
I think we can just change the input text font. Like I said, you might need to adjust the size of the input box, though.

**Comment by wabain** [comment]
I have this implemented. The transition from the placeholder to Volpiano input is kind of awkward though, especially on Chrome.

**Comment by wabain** [comment]
Not 100% happy with my implementation, but I think it's good enough. Feel free to re-open this. It's live on dev-cantus now.

**Comment by ahankinson** [comment]
Looks good enough for show biz. :)

Thanks.
