### ISSUE TITLE
Fallback value for genre

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#210]
I'd noticed that the genre of some chants was listed as "Error," but assumed it was some kind of liturgical term. Looking at the abbreviation expander script though, it seems like that's used as a fallback value if it can't match the genre code.

@ahankinson should the fallback value be the abbreviation instead? Most of the time, it seems that would just make it an empty string.

**Comment by jeromepl** [comment]
One of the possible genres is 'Unknown', that could also be the fallback value

**Comment by wabain** [comment]
But they're not necessarily the same thing. Unknown could signify that an
expert couldn't identify it, whereas blank could mean that no one's gotten
around to it or something.
On Jun 1, 2016 10:27 AM, "Jérôme Parent-Lévesque" <notifications@github.com>
wrote:

One of the possible genres is 'Unknown', that could also be the fallback
value

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DDMAL/cantus/issues/210#issuecomment-223009524>, or mute
the thread
<https://github.com/notifications/unsubscribe/AHTAa6oInkqHwumAcquAZ7EU9691gISGks5qHZbGgaJpZM4FRoX_>
.

**Comment by jeromepl** [comment]
Fallback value has been changed to be the abbreviation itself in c40769b44e7dd4590e144b611f1bb41b056204fc
