### ISSUE TITLE
DEBUG=True on in the production web app

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#213]
This should probably be turned off, but not until after tomorrow in case it does something unintended.

**Comment by ahankinson** [comment]
This should be addressed now.

**Comment by wabain** [comment]
I'm going to take care of this tomorrow. The issue is that nginx isn't configured to work with Django, so I'll need to set that up.

**Comment by ahankinson** [comment]
:confused: 

How is it configured, if not with nginx?

**Comment by wabain** [comment]
Actually that was wrong. I was going off [old documentation](https://github.com/DDMAL/cantus/blob/68f317df98d8129d19e6af584262f04ff234ca7a/public/documentation/nginx_conf.txt) that said to use FastCGI, but that probably isn't right. It's giving a 400 though, so I'll need to find the fix for that.

**Comment by wabain** [comment]
Actually just needed to set ALLOWED_HOSTS. dev-cantus is running now. I'll kick the tires there a bit and then do the production site.
