### ISSUE TITLE
Strengthen front-end linting settings

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#216]
Currently, our JSHint configuration doesn't catch much (for instance, globals or unused variables). We should probably introduce stronger settings. I could also add [JSCS](http://jscs.info) for style linting.

**Comment by ahankinson** [comment]
FYI

https://github.com/DDMAL/RodanClient/blob/master/.jshintrc

**Comment by ahankinson** [comment]
FYI

https://github.com/DDMAL/RodanClient/blob/master/.jshintrc

**Comment by wabain** [comment]
:+1:
