### ISSUE TITLE
Switch from RequireJS to Webpack

### ISSUE THREAD

**Issue by wabain** [DDMAL/cantus#219]
RequireJS was initially designed to provide a way of loading JavaScript dependencies asynchronously, allowing libraries to specify and request their dependencies from the server on the fly. In practice, we don't really make use of this feature. Instead, we use RequireJS to bundle all our dependencies into a single file. Because of this, our build process and configuration is considerably slower and more complicated than it would be using newer alternatives such as Webpack or Browserify, which are designed with this kind of bundling as a core feature. (The way we load JavaScript is also unnecessarily slow from a user perspective, although that could probably be fixed while continuing to use RequireJS.)

Since Webpack has built-in support for RequireJS's AMD module format, switching to it requires no refactoring of the JavaScript source code (with the exception of the configuration code). Switching will gives us considerably more flexibility during development. I actually tried making the switch last week as an experiment and got almost everything working almost immediately. I just need to sort out some Diva dependencies and review the `gulp watch` command and then it should be good to go.

**Comment by ahankinson** [comment]
How much more work would it be to switch to `jspm` and unify our build framework across CU, RodanClient (@magoni), and Vis Client (@mrbannon)?

**Comment by wabain** [comment]
It would be a little finicky to work out the shimming again (although not impossible). My main concern is with reloading files during development. With Webpack rebuilding is very  fast (<= 500ms) and then only one script dependency needs to load. With jspm [I gather](https://github.com/jspm/jspm-cli/issues/872) that the current solution is to rely on external tools to optimize the development workflow, although jspm specific tooling is in the works.

Personally, my preference would be to wait for that side of things to mature, since there's no current need for ES6 support in CU.

**Comment by ahankinson** [comment]
Makes sense. Thanks for looking into it.
