### ISSUE TITLE
Visual neume search interface

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#224]
We should extract single exemplars of neumes from the page images and allow people to click on them, visually assembling a search query by stringing together neumes without needing to know their names.

As well, instead of displaying the names of neumes we should show the page image snippet in the OMR search results by assembling a IIIF URL from the Solr results and then querying the IIP server.

It's a pretty big enhancement, but it would be great if we could get this done before the end of August. @wabain if you think this is not possible feel free to push the milestone later.

**Comment by wabain** [comment]
I think the neume exemplars should be fine, although maybe I'm being optimistic. Showing image snippets in the result should be fine too. We already have the bounding boxes, after all.

**Comment by wabain** [comment]
Opening a [separate issue](https://github.com/DDMAL/cantus/issues/225) for showing images in the search results.

**Comment by wabain** [comment]
I've got the basic functionality done. This terrible gif gives the idea:

![visual_neume_search](https://cloud.githubusercontent.com/assets/7651435/9092151/49eee39a-3b72-11e5-853a-50490994dbdc.gif)

If that looks about right I'll just write some manage.py things to facilitate selecting the exemplars.

**Comment by ahankinson** [comment]
Yeah, I think that looks about right

**Comment by wabain** [comment]
Closing this now that some layout nits are dealt with. The main thing remaining on this is just to select exemplars for manuscripts other than Salzinnes.
