### ISSUE TITLE
Better documentation for advanced searches

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#244]
Provide users with a list of fields and possible values to use in an advanced search in the "All fields", e.g., 

`genre:Antiphon AND mode:8 AND volpiano:ccdc`

Right now this is possible, but users don't know what the specific values of the string fields can be.

**Comment by jeromepl** [comment]
This needs to be generalized to all searches.
A small text explaining how to search the different things should be added to each search types.

I am imagining a small question mark icon to the right of the input field that would make a small pop-up come out.

Furthermore, an explanation of what the data represents can be found on the [cantus database website](http://cantusdatabase.org/description). A link to this page should be provided somewhere.
