### ISSUE TITLE
Update the Volpiano Font

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/cantus#262]
There is a new version of the volpiano font (Volpiano version 5). We should update the font files and create a web font.

**Comment by ahankinson** [comment]
That was quick!

**Comment by jeromepl** [comment]
Reopening: Need precision on which characters are new/have changed. I found low F (character '8' and '(' ), but there is also a mention of a "reassigned character" in the email from Debra Lacoste. We need to update both the server side and the client side so that all characters representing the same note are grouped and do not affect search queries.

**Comment by jeromepl** [comment]
Haven't seen any issues with it so far: closing this.
