### ISSUE TITLE
Gamera classification process on Hartker "movie"

### ISSUE THREAD

**Issue by KateHelsen** [DDMAL/cantus#264]
Andrew Fogarty, we talked about me listing an issue about this. :-) Thanks!

**Comment by AFFogarty** [comment]
📝 :smile:   😄 🎬     🎥::bowtie:

**Comment by KateHelsen** [comment]
:smile:

**Comment by AFFogarty** [comment]
I recorded a 10 minute video showing some Hartker glyph classification.  Should the video be silent or have narration?

**Comment by fujinaga** [comment]
It would be nice to have narration.

**Comment by KateHelsen** [comment]
Seconded.
Thanks!!!
K

-----Original Message-----

**Comment by KateHelsen** [comment]
Wondering if I might be able to have a version of the video Fogarty recorded for a meeting I have with Mark Daley on Wednesday (June 15) morning. Nothing super official, but he wants to know more about our stuff and I thought having that video would be handy. I don't need narration.

**Comment by AFFogarty** [comment]
Sent via email.
