### ISSUE TITLE
Utrecht manuscript is currently accessible through the manuscripts page

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/cantus#266]
This manuscript should not yet be public and thus the link on the /manuscripts page should redirect the users to the source of this manuscript.

Does anyone know what link we should put there? The Cantus Database does not seem to have a source for it.

**Comment by ahankinson** [comment]
http://www.diamm.ac.uk/jsp/Descriptions?op=SOURCE&sourceKey=1355
