### ISSUE TITLE
Provide better dynamic statistics

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/cantus#267]
The /manuscripts page already has some statistics, but we should add more, such as:

- Number of folios
- Number of records
- Number of notes

There is also a way to know from the cantus database which of those have been entered and which have been edited. This could also be used for more statistics (e.g. percentage of completion).

This could either be done on the /manuscripts page or in a totally new page, any suggestions?

**Comment by ahankinson** [comment]
I think at `/manuscripts/` would be fine.
