### ISSUE TITLE
Zoom levels are not preserved with URL

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#280]
If you do a search and click on a result and then zoom the page image, the URL in the location bar does not reflect the page zoom information. (It is correctly kept in the "link" button in Diva).

Further, if you copy and paste a link to a zoomed view in the location bar (another browser or tab), it strips out the zoom information.

**Comment by jeromepl** [comment]
Refs #243

**Comment by musicnerd** [comment]
I actually have my browser setting to a default zoom level, and because of this could only see 3 of my 8 results because there was no ability to scroll.  A typical Cantus user may not realize that.
