### ISSUE TITLE
Cache Manifests on server

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/cantus#281]
Since we decided to start using URLs to point to manifests instead of storing them ourselves, the page construction time on the client side started to take a lot longer. The reason for that is that Diva is waiting to receive the manifest from the server, which is now slower because of the following: In order to avoid mixed content errors, I had to proxy the manifests through a Django view (This view basically grabs JSON from a URL and returns it).
This could be optimizing by caching manifests on the server and refreshing them when they are requested and haven't been refreshed in a little while (A week maybe?)

**Comment by ahankinson** [comment]
Related to DDMAL/musiclibs#114

I wonder if it's worth looking at a generalized caching system, like a big memcached or redis store that we can hook up to both musiclibs and cantus for sharing manifests, thumbnails, etc, keyed by the remote URL.

Thoughts?

**Comment by lexpar** [comment]
Like run a big cache on a CC server with many gigs of ram?

**Comment by ahankinson** [comment]
Ayup. Bigagytes and bigagytes of the RAM. 🐑 

We need to use up all the resources on CC so that we can make the case for more next year (or at least keeping the stuff we have now)
