### ISSUE TITLE
Allow data dump file upload in folio mapping interface.

### ISSUE THREAD

**Issue by jeromepl** [DDMAL/cantus#282]
Instead of requiring that the data dumps file be put in a specific folder on the server and that the chants already be imported, we should allow uploading a data dump file through the folio mapping interface.
The file could then be automatically imported in the Django DB and in Solr and the folio mapping process could continue as usual.
The problem with this is that the import process takes a really long time and we have no way of giving the user any sense of progress.

A possible solution would be to use Celery to create a task of importing the chants and poll a view that gets the status every few seconds on the client side. (Same as https://github.com/DDMAL/musiclibs/blob/master/misirlou/views/status.py)
This requires a lot of setup (Celery + something like RabbitMQ for communication, and optionally Redis) so I am currently researching solutions easier and better suited for this specific problem.

Refs #279

**Comment by ahankinson** [comment]
I'm still baffled why this takes so long. Could you post a link to the code that takes a long time to run?

**Comment by jeromepl** [comment]
Currently optimizing it! Will reference this issue once I commit and update with a few statistics of running time.

**Comment by jeromepl** [comment]
I forgot to mention here that bulk_create did not work as it does not fire the usual pre/post save signals. Instead, I used the transaction.atomic decorator, which improved performance, but not as much as I had hoped.

**Comment by napulen** [comment]
No longer necessary. The csvs (data dumps) are loaded automatically through the backend now.
