### ISSUE TITLE
provision scripts depend on modules that don't exist

### ISSUE THREAD

**Issue by mrbannon** [DDMAL/cantus#288]
solr 6.1.0 no longer available public
https://github.com/DDMAL/cantus/blob/master/etc/provision/setup-solr.sh#L32

postgres 9.3 no longer available
https://github.com/DDMAL/cantus/blob/master/etc/provision/setup-solr.sh#L32

These should be more generic requirements.

**Comment by napulen** [comment]
Specific versions are available in the new provisioning script. These requirements should be updated in general anyway (Python 3, django > 1.7, etc.)
