### ISSUE TITLE
Volpiano font web page

### ISSUE THREAD

**Issue by FaWeRe** [DDMAL/cantus#291]
I would like to inform you about the new Volpiano font web page:
www.fawe.de/volpiano
At the moment it is only available in German, but an English translation is in preparation.

This will be the only "official" Volpiano web page, please delete all copies of the font files on your servers and redirect on the new site.
David Hiley and me are very proud that Volpiano became a very useful tool for chant research since 2003. Nevertheless it’s important, that since then all versions of Volpiano are on the one hand free for use, but on the other hand protected by copyright. So a permission is necessary for any conversion also. The license within every zip-file of the official download-page contains further information,
Our aim is not to prevent any research or development but to have one consistent source for the font with an overview about all changes etc. It's also provided to offer the creation of additional font files with special symbols and the possibility of their integration into the "official Volpiano family" in the future. Further details will be announced at the reactivated Volpiano website and also via email. 

Best regards,
Fabian Weber

**Comment by napulen** [comment]
Sorry for the long (long) wait on this. We'll be serving the font from your site rather than redistributing it.
