### ISSUE TITLE
Cantus Ultimus summer 2019 overview

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/cantus#292]
- [x] Create Docker container for app deployment  
- [ ] Streamline process for populating manuscripts
- [ ] Improve CU documentation for importing and displaying manuscripts  
- [ ] Create a workflow to upload a set of images on a IIIF server and create manifests

**Comment by napulen** [comment]
Container thread in #293, reusing the Vagrant one for now. I do think it is better to move to Docker eventually. Working out the Vagrant one is not a waste of time, most of that work can be recycled for Docker.

**Comment by napulen** [comment]
Container is ready. The next priority of the project is the second one listed here **Streamline process for populating manuscripts**. Expected time for completion is March 2020, having the capability of third-party users being able to add new manuscripts without much more than a few links and revising the automatic mapping provided by the website. 

Replacing this issue with issues of the individual steps necessary for the streamline process.
