### ISSUE TITLE
Separate the structure of the project/apps in Cantus Ultimus as recommended in the django documentation

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#294]
The way it looks now, it seems like the `cantusdata` folder contains the project settings (`settings.py`) but it also contains `models` and `views`, which belong to what the django documentation abstracts as *the apps in a project*. I think it is best to follow the structure from the django documentation, otherwise it is confusing when maintaining the code.

**Comment by fujinaga** [comment]
Fine with me.

**Comment by napulen** [comment]
I'm looking at this right now, `cantusdata` is both, a project and an app. It has the settings of the project and the models/views. The name (`cantusdata`) is also not great to figure out that it is the folder that holds everything together.

A way of organizing the repository that is closer to the examples in the django documentation could look like this:

```
root
|-- cantusultimus
|    |-- settings.py
|    |-- ...
|
|-- cantusapp
|    |-- models
|    |-- views
|    |-- ...
|
|-- neumeeditor
| .  |-- models
| .  |-- views
| .  |-- ...
```
`cantusultimus` is the project, holding all the urls, wsgi information, and settings (e.g., database, solr, etc.)

`cantusapp` is an app used by the `cantusultimus` project.

`neumeeditor` is another app used by the `cantusultimus` project

I am doing this as part of the containerization process, as it also helps me to understand the project better.

**Comment by napulen** [comment]
This is gonna be deferred until we have a "reduced" codebase of cantus with `django==1.7`. Lowering priority

**Comment by napulen** [comment]
It takes a significant amount of effort to reorganize the repo. What was easier was to reduce the codebase and that process is done. For the time being, only minimal changes to the organization of the repo (deleting unnecessary files/code) to make it more approachable.
