### ISSUE TITLE
Is the neumeeditor necessary for Cantus Ultimus?

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#295]
This seems to be a separate app, I am not sure it is used anywhere in the website. I need to look further in Cantus Ultimus and also other SIMSSA projects, if this is used somewhere else, maybe it would be convenient to put it in its own repository?

**Comment by fujinaga** [comment]
Can you find out who developed this?

**Comment by napulen** [comment]
I confirmed that It is loaded as a django app in the project, so it is probably used somewhere. Need to figure out where that is.

I will also take a look into who developed this.

**Comment by napulen** [comment]
Update on this: I checked the commit history. This app was introduced into the project in 2014 by Andrew Fogarty.

It is accesed in the website by going to url/neumeeditor/. For example: cantus.simssa.ca/neumeeditor/

If you visit that link in our production and staging instances, it is disabled/not working, however, when I deploy the app I can see the interface.

I will get further into this while I am working on the container, and for now, I will just leave it there, but my guess is that we won't need it anymore.

**Comment by fujinaga** [comment]
This may be related to https://github.com/DDMAL/CantusEditor

The idea might have been to edit directly from the Cantus Ultimus website.

Anyways, don’t worry about it for now.

We would have to make https://github.com/DDMAL/CantusEditor working again, once the CU website workflow is completed.

**Comment by napulen** [comment]
> We would have to make https://github.com/DDMAL/CantusEditor working again, once the CU website workflow is completed.

It should be working: https://ddmal.github.io/CantusEditor
or do you mean working within the Cantus Ultimus website?

Respecting the `neumeeditor` app, I will just leave it there for now, it doesn't really affect anything. I have been just trying to simplify the organization of the project as much as possible in the interest of future developers.

**Comment by fujinaga** [comment]
> On Jul 30, 2019, at 9:38 AM, Néstor Nápoles <notifications@github.com> wrote:
> 
> We would have to make https://github.com/DDMAL/CantusEditor working again, once the CU website workflow is completed.
> 
> It should be working: https://ddmal.github.io/CantusEditor
Yes, it’s working now, For some reason it wasn’t working last night.

> or do you mean working within the Cantus Ultimus website?
> 
No.
There should be an instruction as to how to add other manuscripts, however. Low priority.

> Respecting the neumeeditor app, I will just leave it there for now, it doesn't really affect anything. I have been just trying to simplify the organization of the project as much as possible in the interest of future developers.
> 
That’s fine.

**Comment by napulen** [comment]
> Yes, it’s working now, For some reason it wasn’t working last night.

It should be an issue with GitHub, we've had a few issues related to GitHub lately.

> There should be an instruction as to how to add other manuscripts, however. Low priority.

In Cantus Editor? If so, I will write the issue in that repo and come back to it at some point.

**Comment by fujinaga** [comment]
> On Jul 30, 2019, at 9:52 AM, Néstor Nápoles <notifications@github.com> wrote:
> 
> Yes, it’s working now, For some reason it wasn’t working last night.
> 
> It should be an issue with GitHub, we've had a few issues related to GitHub lately.
> 
> There should be an instruction as to how to add other manuscripts, however. Low priority.
> 
> In Cantus Editor?
Yes.

> If so, I will write the issue in that repo and come back to it at some point.
> 
Thank you.
