### ISSUE TITLE
UI improvements of the Play Audio button

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#312]
- [x]  There should be a `stop` function (button).
- [x] The `Play Audio` button should be deactivated until the chant finishes or it is stopped.
- [x] The `Play Audio` button should be absent when there's no Volpiano.
- [x] Fix playback issues in Safari
- [x] playback should handle liquescents (right now has a gap)
- [x] playback should hand b-flats (currently treats them like naturals)
- [x] could stand to be a hair faster...(takes a long time to play the chants, esp. since you can't stop/pause)
- [x] maybe treat | as a rest?
- [x] Notes play on top of each other when playing chant for first time after page load
- [x] Play button does not have unique id (plays first expanded chant on page)

**Comment by napulen** [comment]
@jacobsanz has a fix for improvement 3.

**Comment by annamorphism** [comment]
would like to add:
-playback should handle liquescents (right now has a gap)
-playback should hand b-flats (currently treats them like naturals)
-could stand to be a hair faster...(takes a long time to play the chants, esp. since you can't stop/pause)
-maybe treat | as a rest?

**Comment by napulen** [comment]
Moving to `high priority` queue after Ich's conversation today in the lab meeting

**Comment by fujinaga** [comment]
Only if it's a quick fix, i.e., a couple of days of work.

**Comment by napulen** [comment]
Probably yes to quick fix. We'll look at it.
