### ISSUE TITLE
Dockerize cantus ultimus(?)

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#327]
It takes a while (~10 minutes) to fire up a cantus vagrant box from scratch. Maybe doing docker would be faster/better. The technology is certainly more popular now.

Not a priority, but maybe we want to migrate all of the container to Docker.

Also, I suspect that Docker would be faster, but I am not certain that it will.

**Comment by napulen** [comment]
Keeping Vagrant for the foreseeable future. Focus has to go in making `solr` integration more efficient.

**Comment by napulen** [comment]
It seems we are doing this after all

**Comment by napulen** [comment]
The reason for doing it is more about Docker being more and more ubiquitous everywhere, while Vagrant seems to be getting behind (e.g., buggy WSL support, less documentation, etc.)

In principle, both containerization can coexist, if a `Docker` one is implemented and stable, that can become the only containerization solution in the future (end of Summer 2022?).

**Comment by napulen** [comment]
Also, @eliwaksbaum, if you think this requires to break down the problem into several subproblems (e.g., enabling `solr` container in docker for cantus ultimus, etc.) feel free to create related issues.

**Comment by eliwaksbaum** [comment]
Running into a roadblock with populating the postgres database. I've confirmed the database, user, and django migrations are all working as intended, there's just no data in there. Do you know where in the Vagrant setup the data actually gets inputted?

**Comment by eliwaksbaum** [comment]
my bad, misclick

**Comment by napulen** [comment]
I just saw this comment on the email thread of this issue
```
Running into a roadblock with populating the postgres database. I've confirmed the database, user, and django migrations are all working as intended, there's just no data in there. Do you know where in the Vagrant setup the data actually gets inputted?
```

Is this still an issue?

**Comment by napulen** [comment]
I think I understand what you mean, if you are talking about manuscript data imported from Cantus DB, it doesn't exist right after the vagrant provisioning.

It exists after going through this part of the documentation: https://github.com/DDMAL/cantus#initialize-a-newly-launched-website

However, right after this (in the vagrant provisioning)

```python
python makemigrations
python migrate
```

You should already have some tables in postgres from the django models.
