### ISSUE TITLE
Conditional requirement in Vagrantfile

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#338]
Require the `openstack-provider-plugin` only when openstack is chosen as the provider.

It should not be necessary to have it when running with VirtualBox, however, it is currently a requirement anyway in the Vagrantfile.

**Comment by napulen** [comment]
This should probably be a change in the `Vagrantfile` setup. People who are always working locally shouldn't need the `openstack-provider-plugin` installed to run `vagrant up`.

**Comment by dchiller** [comment]
Should we do this given the move to docker? 

I presume if so that this should be a PR to main_predocker...

**Comment by napulen** [comment]
This issue only makes sense for Vagrant, considering closing if we are not supporting Vagrant anymore.

Let's talk about Vagrant's future later today
