### ISSUE TITLE
Protect database passwords through environment variables

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#355]
Define environment variables for the database

```python
DATABASES = {
    "default": {
        "PASSWORD": "ThePassword",
     }
}
```

**Comment by napulen** [comment]
They should be implemented in a similar way as other environment variables: https://github.com/DDMAL/cantus/issues/352

**Comment by napulen** [comment]
The hint here is to look at the provisioning script for environment variables. For example, how we've setup the `DJANGO_SECRET_KEY`.

**Comment by eliwaksbaum** [comment]
this can be included under the `environment:` section in docker-compose for the app and postgres services, then read from in settings.py. then we'd need to generate the key before we run `docker-compose up`, like in a shell script, but that could lead to issues when building on different os's

**Comment by dchiller** [comment]
Or I guess we wouldn't need to create a separate env file -- just have developer/deployer add to the one that is already there.

**Comment by eliwaksbaum** [comment]
yeah .env is already there. that sounds great from a docker viewpoint. security wise, can people be trusted to input appropriately secure passwords? does the password itself matter, or just that it's hidden in an env variable and not in the repo?

**Comment by dchiller** [comment]
yeah, idk....does the lab have any best practices we follow for choosing passwords for services we are deploying on compute canada? But yeah, I feel like first step is not having whatever password it is (even if not so secure) on the public repo.
