### ISSUE TITLE
Fragment images are rotated in US-CApc D-0io1s

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#373]
After carefully inspecting what we do with the IIIF manifests, I concluded that we are not rotating the images at all.

It seems getting the default thumbnail size from the IIIF manifest already comes rotated.

This is a link constructed by the folio mapper: https://fragmentarium.ms/loris/F-io1s/Q_front.jpg/full/,160/0/default.jpg

**Comment by napulen** [comment]
In the fragmentarium viewer, they rotate them:

![image](https://user-images.githubusercontent.com/7258463/120340648-3ac06d00-c2c4-11eb-93f0-5cffdda55916.png)

**Comment by napulen** [comment]
Relevant section is the end of the highlighted line: `/90/default.jpg`. There is a 90 degree rotation in all images.

So we have to rotate them. 

I don't see how else to implement this other than hardcoding rotation for specific manuscripts/libraries.

**Comment by napulen** [comment]
We need to make the hardcoding in at least two places:

```
public/cantusdata/frontend/public/js/app/utils/pageSnippetUrl.js
public/cantusdata/views/map_folios.py
```

**Comment by fujinaga** [comment]
One solution may be is to provide a global rotate button in Diva for a manuscript.

**Comment by napulen** [comment]
Rotate button would be a good solution for the viewer, but we use the IIIF images in some other places (e.g., folio mapping interface).

@fujinaga decided that, given this seems to only affect this manuscript, it won't be fixed for now, as it requires us to hardcode rotations based on manuscript id
