### ISSUE TITLE
Verifying integrity of solr data

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#387]
I am under the impression that several existing issues (https://github.com/DDMAL/cantus/issues/380 https://github.com/DDMAL/cantus/issues/382 https://github.com/DDMAL/cantus/issues/384 https://github.com/DDMAL/cantus/issues/385) are all related to our solr backend malfunctioning.

This is very difficult to debug, because we are wrapping core operations in django (e.g., creating a new manuscript entry) with a solr wrapper that pushes the data to solr.

It is difficult to know if this process fails for certain manuscripts, or with asynchronous operations (e.g., several manuscripts being imported concurrently), or because of network issues (because the push operations will communicate with solr, which is in a different running process, via the local network and a port).

I have been working on a way to test this process.

For now, the best strategy has been to import some chant data, and generate a full json dump of everything that is in solr right after. The idea is that, if we query correctly (e.g., for all chants associated with a given manuscript and sorted by folio number in ascending order), different workflows (e.g., importing several chants concurrently, or different pairs of manuscripts one after another) should generate the **exact same json dump**. If something is going wrong, two json dumps will fail a `diff` comparison.

Importing a manuscript generates ~9MB of text data in the json file, so the `diff`ing is also somewhat cumbersome, it's impossible to run it on vscode without hanging the process. So far, using the unix `diff` tool works. That's what I've been doing. 

I still don't have meaningful results out of this process, but I think I'll have them soon.

**Comment by napulen** [comment]
I made the first test:
1. Imported all the chants in `15181` and dumped the full json dump of this query: ```http://localhost:8080/solr/collection1/select?indent=on&q=type:cantusdata_chant%20AND%20manuscript_id:138&rows=6000&sort=folio%20asc,%20item_id%20asc&wt=json```
2. Imported all the chants in `Salzinnes`, and dumped the full json dump of the chants related to `15181` (same query as in 1)

The 2 json files were identical.

**Comment by napulen** [comment]
I am going to import a couple more manuscripts, probably simultaneously, and check again the integrity of 15181.

The tricky thing is that we need to make several combinations. For example, what happens if I first imported `Salzinnes` then `15181`. Or if `15181` was the nth manuscript imported and there was a bunch of information already in the index.

**Comment by ahankinson** [comment]
I’m not sure what Solr library you are using to wrap it, but under the hood most of them are very simple Wrappers around HTTP. So there is not a lot that can go wrong there.

Having a look at the Solr synchronizer class in the signals — there’s a lot going on there, and it’s not immediately obvious how this gets triggered. If you’re doing a lot of saves to the database and the signals are firing off after every save, there is a lot of potential for tripping up the synchronization process. A save could trigger a delete from Solr, but this may have a second save happening at the same time…

One way to break this down is to disable the signals, import the data into the database, and then run a complete reindex manually. That should tell you if it’s the signals sync bit or not.

**Comment by napulen** [comment]
The `signal` wrappers is what I am referring to. I've vetted this code at least twice. It's well written and seems to be efficiently opening a single "connection" to solr and doing several operations at once when multiple entries are updated simultaneously.

However, I am under the impression that the system is much slower than it should, and we also have these arbitrary 504 responses that I can't really pinpoint to anything else than the `signal` wrappers.

I was thinking the same thing, to "disconnect" the signals and see how that works. It should also reveal if the performance bottleneck is located there. 

I don't think it is easy to "disconnect" the signals tho. That's why I started by making sure that everything plugged in "as-is" should output the same json files regardless of the order and amount of transactions that you send via the admin interface.

**Comment by ahankinson** [comment]
I have had problems in the past with 'keepalive' connections in a Python library causing weird collisions when doing multithreaded indexing. The solution was to open a new connection for each call instead of using sessions. If you're using solrpy, it's probably keeping a session open under the hood.

For reference, this is what we are using to index a list of Python dictionaries to Solr:

```python
def submit_to_solr(records: List) -> bool:
    """
    Submits a set of records to a Solr server.

    :param records: A list of Solr records to index
    :return: True if successful, false if not.
    """
    log.debug("Indexing records to Solr")
    res = httpx.post(f"{solr_idx_server}/update",
                     data=ujson.dumps(records),
                     headers={"Content-Type": "application/json"},
                     timeout=None)

    if 200 <= res.status_code < 400:
        log.debug("Indexing was successful")
        return True

    log.error("Could not index to Solr. %s: %s", res.status_code, res.text)

    return False
```

(This supports indexing > 5 million documents in about 20 minutes using 8 processes).

It would probably be fairly trivial to replace your current solrpy with this to see if it makes a difference.

**Comment by napulen** [comment]
Thanks for the snippet. I will try this out.

I also want to find a way to systematically trigger the issues we've observed. If we ever experience similar problems, I want to be sure that there is a method we used to verify that something was fixed.

**Comment by napulen** [comment]
@dchiller this snippet shared by @ahankinson is an alternative for the `solrpy` stuff we have on `solr_index.py`. It might help you on your new quest.
