### ISSUE TITLE
Two-folio layout in IIIF: 500 server crash 

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#392]
Trying to use this manifest (https://adore.ugent.be/IIIF/manifests/archive.ugent.be%3A082FD364-C35A-11DF-A9D6-99EF78F64438) results in a 500 error on Cantus Ultimus staging. It's possible that something in the structure of the IIIF manifest doesn't work well with our parsers.

**Comment by napulen** [comment]
This crash was reported by Alessandra Ignesti after trying to import the IIIF manifest through the Cantus Ultimus admin interface.

**Comment by napulen** [comment]
This is one of the unsupported IIIF manifests I was talking about today, @eliwaksbaum 

If you try to import it using the process documented on the README
- import chants
- indicate IIIF path in manuscript 
- mark as `public`
- run `admin/map_folios` interface to map its folios to IIIF images

at some point, it will crash the web app (500 error).

We need to know why that happens, and who is to blame (is it our parsing of IIIF manifests? The IIIF manifest is weird/invalid? etc.)

**Comment by eliwaksbaum** [comment]
I believe the main problem is that there are two folios per image in this one, which totally breaks the current process

**Comment by napulen** [comment]
The only (and it is a long shot) workaround I can think for that is

- We use IIIF queries to only get one region of the image, corresponding to one of the folios
- We map everything on top of those IIIF queries, so that we can get "one folio at a time" and operate as usual

**Comment by dchiller** [comment]
For reference, this IIIF manifest refers to:

Utrecht, Universiteitsbibliotheek, Ms. 406 (shelfmark 3 J 7) | NL-Uu 406 (3 J 7)

**Comment by dchiller** [comment]
I think this can be closed by #555 ?

**Comment by napulen** [comment]
Yes, closing and
