### ISSUE TITLE
/folio-set/manuscript/... not found

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#407]
When viewing a manuscript on the docker version django or maybe gunicorn outputs something like: `Not Found: /folio-set/manuscript/25/https://lib.is/IE9434868/iiif/2/FL9435866/`. This is the work of the ManuscriptFolioSetView as called by FolioView.js

I didn't notice it before because nothing seems to go wrong. All the folio images show up fine. What would we expect from this sort of error? Could it be erroneous?

**Comment by napulen** [comment]
This looks like a url rewrite to avoid CORS related issues. It could be erroneous if the iiif manifest url embedded in the larger url leads to an invalid path in the library serving the images of the manuscript. 

Basically, when searching for an image in an external server, Cantus Ultimus makes the request from its own server, and then provides the output to the user. This is done by using a proxy url (as the one shown in your example). You should see in the `urls` file how that proxy url is handled.
