### ISSUE TITLE
Map_folios cannot handle simultaneous submissions

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#410]
Run the server and associate IIIF manifests with manuscripts through the admin interface. Mark manuscripts as public, and import associated chants for the selected manuscripts in the usual way. For this example, Salzinnes and Karlsruhe 60 were used. 

1. Go to /admin/map_folios:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/11023634/169881240-41d3be20-b4fb-42d0-8e91-8591d7add499.png">
2. Map both folios in quick succession.
3. stdout will show a `RuntimeError`. 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/11023634/169881471-37079763-377f-41fd-8c21-3b517ae7ddc8.png">
4. Only one of the mapping jobs will continue/complete:
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/11023634/169882122-c83e68cf-f046-4794-b2c3-43638a89fe99.png">

**Comment by napulen** [comment]
Confirmed this is a serious bug on our `solr`-`django` backend.

**Comment by napulen** [comment]
> I looked at how haystack supports refreshing the index, and it looks like what it supports is kind of like what our own approach already does

That's huge, thanks for looking into that

**Comment by dchiller** [comment]
Yes: by reading the docs I meant reading the django-haystack documentation on indexing.

**Comment by dchiller** [comment]
A few developments:
1. I looked over the solrpy (what we currently use) code and pysolr codebase, and although pysolr has slightly more recent development and provides a few more functions, it seems to me that they are both essentially wrappers around some url encoding for http requests to the solr server and some xml parsing of the responses for python. It does not seem to me that either offers substantially better functionality, and so would tentatively say that there is no need to change from solrpy at the moment. 
2. It does seem like the primary concurrency issue was in our instantiation of the solr_sync signal and NOT in the refresh_solr commands. Map_folios processes seem to be able to run just fine concurrently if the signals are disconnected and all solr indexing is completed after all database interactions. The solr backend handles the requests just fine, and additions to the index from two different concurrent map folio processes are combined in a single solr commit with no problem.

**Comment by dchiller** [comment]
To fix, we decided to detach and then re-attach signals during the map_folios process, running a batch refresh process on the solr index for folios and chants associated with the mapped manuscripts after all postgres transactions have been completed. 

Currently:
- Testing to ensure that this has no impact on the solr index, but does allow for simultaneous mapping of manuscripts. 
- Implementing A procedure to ensure that signals were re-attached only when the final concurrently mapped manuscript was finished mapping.

TO DO: A complete solr index refresh should be executed at some interval to ensure that unrelated postgres changes made during the time that signals are off are indexed at some point. This needs to be implemented for production.

**Comment by dchiller** [comment]
Draft pull request at #426

**Comment by dchiller** [comment]
> To fix, we decided to detach and then re-attach signals during the map_folios process, running a batch refresh process on the solr index for folios and chants associated with the mapped manuscripts after all postgres transactions have been completed.
> 
> Currently:
> 
>     * Testing to ensure that this has no impact on the solr index, but does allow for simultaneous mapping of manuscripts.
> 
>     * Implementing A procedure to ensure that signals were re-attached only when the final concurrently mapped manuscript was finished mapping.
> 
> 
> TO DO: A complete solr index refresh should be executed at some interval to ensure that unrelated postgres changes made during the time that signals are off are indexed at some point. This needs to be implemented for production.

I pursued a different approach that allowed us to keep the use of signals basically as is and removed the need to detach and re-attach signals (and ensure that was happening in the right order). See PR #426 for details.

Testing was completed, and the solr index looks the same with this and the previous method. 

There is no need (as a result of this change) to run a regular solr index refresh, but maybe an open question whether that would be good to add.

**Comment by napulen** [comment]
@dchiller Yes! Sorry that I lost track of all the discussion here. I think #426 got this one. If the issue ever comes back, we can reopen and continue.
