### ISSUE TITLE
staging vs production in docker

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#411]
need to signify if the build is running in a staging or production environment so we can correctly set django's DEBUG setting. (I think that's all that variable is being used for in vagrant)

**Comment by napulen** [comment]
Yes, I believe that is the only thing we do with it.

**Comment by eliwaksbaum** [comment]
```
# Don't Touch!!
COMPOSE_PROJECT_NAME=cantus

#Sets the DEBUG Django setting
#DEBUG = true for staging, DEBUG = false for production
DEBUG=true
```
@napulen does manually changing a line in the .env file seem like an ok way to do it?

**Comment by napulen** [comment]
I was skeptical about it, but looking at the documentation, it seems that's a common way. So yeah, this works.

**Comment by napulen** [comment]
Just two things:

- From the documentation: `Values set in the shell environment override those set in the .env file.` Just to be aware
- Production is more pedantic and Staging is more permissive, I'd do pedantic the default and people can override that when they are developing
