### ISSUE TITLE
solr data persistence

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#412]
writing solr's data to /var breaks certain systems. We can write it somewhere else (in collection1/conf/solr-config.xml), but the question is whether we should bind that directory to a docker volume so the data persists. Without the volume, it seemed like loaded manuscripts, users, and all that was persisting fine through taking the containers up and down. What is solr writing in there?

**Comment by eliwaksbaum** [comment]
did some more testing and it really seems like we don't need to save the solr data. @napulen does that make sense? in that case we can just save the data to the default location, which the solr user should have permission for

**Comment by napulen** [comment]
Sounds good! If things go south, let's remember this issue and the decision made. We can always revert back.
