### ISSUE TITLE
Extending pool of supported manuscripts

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#413]
A few issues are scattered around: #319 #392 #386 

The underlying purpose in these has been to increase the number of manuscripts that Cantus Ultimus can serve to the public.

For one reason or another, sometimes those manuscripts can't be imported (e.g., CORS-related issue, 500 server crash, etc.)

We want to focus on mitigating the necessary issues in the codebase, so that more manuscripts can be served online.

**Comment by dchiller** [comment]
I'm closing this issue. #392 is closed. #319 and #386 have recent updates (as of 8 May 2023) that should allow them to be closed or fixed shortly.
