### ISSUE TITLE
Merging the dependabot pull requests

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#416]
The reason why I generally don't automerge the PRs by `dependabot` is because they sometimes break our code (a side effect of not running the latest django always).

However, I have not tried the existing ones #389 #390 #393

The django one is technically just a patch revision, so it might be okay.

**Comment by eliwaksbaum** [comment]
Pretty sure pillow and lxml aren't even used (progressbar2, wheel, and coveralls neither) so I think we can ignore those two.

**Comment by napulen** [comment]
Ok, so then we only need to check the `django` patch

**Comment by dchiller** [comment]
Rebuilt the containers with django 3.1.13 -- everything seems to be working well (importing data, mapping folios, site navigation, manuscript details pages, search)

**Comment by napulen** [comment]
All of these closed. They were pointing to an older version of `main` anyway. And some of those dependencies are gone entirely.
