### ISSUE TITLE
Run unittests with github actions

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#417]
The Cantus Ultimus repo needs some Continuous Integration.

For starters, what I think we need:
- On `push` and PRs to the `main` branch, we want to run a check for `black` formatting all across the python codebase
- On `push` and PRs to the `main` branch, we want it to run unit tests and pass

**Comment by eliwaksbaum** [comment]
finally got it to work sort of. It still fails since actually our current build does not pass the tests, but it fails in they way I though it should, not some other way, which is nice. @napulen when would we want it to run? on a push to a separate development branch? on a merge? people aren't rly pushing directly are they?

**Comment by eliwaksbaum** [comment]
```
Traceback (most recent call last):
  File "/code/public/cantusdata/test/helpers/test_expandr.py", line 44, in test_expand_genre
    self.assertEqual(expandr.expand_genre("Pr"), "Prefatio")
AssertionError: 'Prefatio (when written out and notated)' != 'Prefatio'
- Prefatio (when written out and notated)
+ Prefatio
```
@napulen so this is where it's failing. Is this important? I guess the scraper is catching something extra off the cantus db site?

**Comment by napulen** [comment]
> ```
> Traceback (most recent call last):
>   File "/code/public/cantusdata/test/helpers/test_expandr.py", line 44, in test_expand_genre
>     self.assertEqual(expandr.expand_genre("Pr"), "Prefatio")
> AssertionError: 'Prefatio (when written out and notated)' != 'Prefatio'
> - Prefatio (when written out and notated)
> + Prefatio
> ```
> 
> @napulen so this is where it's failing. Is this important? I guess the scraper is catching something extra off the cantus db site?

Interesting... I need to look at that scraper again. Doesn't seem to be an important fail.
