### ISSUE TITLE
Rewrite vagrantfile to provision dockerized production in compute canada

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#428]
Vagrant for local set-up is no longer required, but portions for provisioning with openstack api are still useful. Add a vagrant file to the dockerized repo for use during remote server provisioning.

**Comment by napulen** [comment]
Marking as `Won't Fix` for now. Let's play it by ear with the existing setup.

**Comment by napulen** [comment]
Current setup is fine. I doubt we need Vagrant at this point. Closing!
