### ISSUE TITLE
`black`ify codebase in GitHub Actions

### ISSUE THREAD

**Issue by napulen** [DDMAL/cantus#469]
I just noticed a few python files that do not have `black` formatting.

In order to reduce future diffs in PRs, it'd be nice to:
- [ ] Make all of our python code comply with `black` formatting
- [ ] have the gh-actions workflow to run `black` before the unit tests, so that it'd fail the build if some source code is introduced without the expected formatting

**Comment by dchiller** [comment]
I wonder if this is a good case for a git hook? I've actually seen that on other projects.

Maybe github actions serves the same purpose (just not as familiar)

**Comment by dchiller** [comment]
Cool, this seems great: https://black.readthedocs.io/en/stable/integrations/github_actions.html

I'll try it.

**Comment by napulen** [comment]
> I wonder if this is a good case for a git hook? I've actually seen that on other projects for `black` specifically.
> 
> Maybe github actions serves the same purpose (just not as familiar)

Yes, in a local development workflow you solve this with git hooks. Unfortunately, you can't run git hooks on github (AFAIK), but github actions basically allows you to do the same and more.

**Comment by dchiller** [comment]
yep yep -- excellent!

**Comment by dchiller** [comment]
yep -- just making sure i understand what it does, and then will push

**Comment by napulen** [comment]
Fixed with #471
