### ISSUE TITLE
Mapping gets "stuck"

### ISSUE THREAD

**Issue by eliwaksbaum** [DDMAL/cantus#479]
Maybe it'll eventually go through, but currently St. Gallen, CH-SGs 390 is refusing to map folios. The original submission was an hour or two ago, I've tried again and nothing seems to happen. Maybe mapping statuses like mentioned in #476 could help here, could have a "mapping failed" status if it takes too long

**Comment by dchiller** [comment]
yeah, that's definitely too long :)

**Comment by napulen** [comment]
We need to verify that this doesn't happen anymore after `celery`/etc.

**Comment by dchiller** [comment]
Confirmed (mapping multiple manuscripts at once, including CH-SGs 390, that this works as expected.
