### ISSUE TITLE
Task progress data in Django admin interface not very user friendly

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#501]
Status of tasks (eg. importing chants or mapping folios) handled by the celery task queue is available in the Django admin interface, but the information provided is not very user friendly (names of tasks are uninformative id's, the only information you get is failure or success, etc.) 

Tbd, but we may want more informative messages/task names, etc.

**Comment by napulen** [comment]
Something I noticed is that we get status `SUCCESS` (can't remember the exact wording) but any intermediate status just shows up as `-`. It'd be nice to have something like `SUBMITTED` | `IN PROGRESS` too
