### ISSUE TITLE
Make link to manuscripts more prominent in the home-page and navbar

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#506]

**Comment by napulen** [comment]
More specifically 
- [ ] Modify the `home.md` markdown to include a link to the manuscripts page there
- [ ] Make the `Manuscripts` button in the header a bit more prominent with some `css` styling

**Comment by dchiller** [comment]
Addressed by #512 and https://github.com/DDMAL/cantus-staticpages/pull/3
