### ISSUE TITLE
Improve volpiano spacing

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#541]
Volpiano excerpts sometimes have overlapping text.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/11023634/180817413-0de38f70-2848-43fe-b1e7-74c4ba070192.png">

**Comment by annamorphism** [comment]
I feel like this  used to happen quite a lot in Cantus DB, but now I can't find any examples, so maybe it got fixed at some point. From overlaying the two results (rather like an eye exam), one can see that the main difference is that the DB font text is significantly smaller compared to the notes, which seems to mostly fix it:
![image](https://user-images.githubusercontent.com/67451875/180875449-99d92889-5192-45cc-b30a-90bfd12df606.png)
I don't *think* anything got changed about the music typesetting but I could be wrong. 

Incidentally, the texts are different: CDB sets the MS text, while CU sets the "standardized" text.

**Comment by dchiller** [comment]
Thank you @annamorphism! 

So, I just put the CU volpiano text font down a size, and it does seem to be doing a lot better....I haven't found an overlap yet!

I don't love this solution, because you never know when there will be a syllable length-note combination that is just off enough to make them overlap even with the smaller size, but maybe this is good enough for now?

Also tagging in @napulen

**Comment by annamorphism** [comment]
I agree it's a little inelegant--even in my excerpt above there's no space between "quem" and "con," and probably on a word like "summa" with two wide consonants in a row there would be a bit of overlap. But it works well enough, without having to deal with different possible lengths and widths of syllables...

**Comment by dchiller** [comment]
agreed :)

**Comment by napulen** [comment]
I am happy with this solution as well!
