### ISSUE TITLE
folio numbers get "stuck" on big scrolls

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#544]
If you scroll from one page to another that has no folio number (e.g. the cover of Salzinnes), the field for folio number stays the same as where you started scrolling, and everything else is (correctly) empty. If you then scroll back down to 1r, the mapping resumes correctly from there.
BUT if you scroll to the end and back up page by page, it will keep saying the same thing!
![image](https://user-images.githubusercontent.com/67451875/180844796-c3c1f7b6-2fe1-4a6f-afab-13ab45dd40fc.png)

honestly not that common a situation but a weird one.

**Comment by dchiller** [comment]
I think there are two simultaneous issues here:

1. The folio number displays
<img width="149" alt="image" src="https://user-images.githubusercontent.com/11023634/180863270-b184e523-3667-4748-b4bb-357929633d33.png">
and 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/11023634/180863332-1191d35d-0135-41db-aa04-19656de17e3a.png">
don't update correctly when the image you have scrolled to are not mapped. They just stay what they were at the last mapped folio you scrolled to. 

In this case, we should probably update those displays to give the page number, ie. in this example, "page 485", so you could still refer to clearly and know where you are in the manuscript, but clearly differentiate it from a named folio. 

2. There are errors in the Salzinnes mapping described in #499 (not sure if they are the exact same in production and staging, but there is definitely overlap). This would explain why there are folios at the end of the manuscript that should be mapped to a folio with chants but are not!

**Comment by annamorphism** [comment]
ah, you're right--the numbers do reappear once you get to a properly mapped folio, which was just a lot farther away than I was anticipating. 

The mapping errors are not the same--staging seems to get out of alignment earlier.  But then the pictures are not the same either.

**Comment by dchiller** [comment]
Perfect, so to-do:

- [ ] Fix Salzinnes mapping with staging images.
- [ ] Make sure page number updates during scrolling even if folio isn't mapped.

**Comment by fujinaga** [comment]
@dchiller I just want to make sure that you are aware of the two sets of digitized images for the Salzinnes manuscript. They have different folio ordering. Both of these versions should eventually appear in CU.

**Comment by dchiller** [comment]
Aha! thanks @fujinaga I was aware of the second set of images, but not that we should serve both! And maybe the image set we are using got swapped between the last production version and these last few staging releases? I will track that down just to confirm it is not something else. 

When we get to the point where we are implementing both sets at once, we should discuss how we want that to look.

**Comment by dchiller** [comment]
@napulen I noticed something as I was re-doing the Salzinnes mapping: when we don't have an existing mapping and there are no useful folio labels in the IIIF manifest (both of which are the case here) we start by naively assigning the folio numbers to each subsequent image in order. 

But, in the case of Salzinnes, the folio numbers we have (from Cantus DB) already have gaps where they should be, so we could get a little more intelligent in our mapping and if our folio records jump from 13v to 15r, we would skip two images (for 14r and 14v) in our naive labeling...maybe that's over-engineering a one-time problem, but maybe something that we should keep in mind if we encounter it with other manuscripts.

**Comment by napulen** [comment]
@dchiller This is true and should already be happening for the "old" Salzinnes images. The URL links in the newer images are not similar to the folio mapping we have from Cantus, so the naive mapping kicks in. Maybe I am missing something, feel free to send an example if you think that's the case

**Comment by dchiller** [comment]
I see -- the "new" images are what's in staging, so that's what I was looking at. 

However, I was just looking to find an example, and it seems like there are just as many, if not more, examples in new Salzinnes where the folios with no chants on them don't fit into the labeling scheme...so, I don't think a feature like I suggested above would actually make mapping any easier.

**Comment by annamorphism** [comment]
@dchiller unfortunately, as you just concluded, there are both situations where the chantless pages have been removed as well as ones where they haven't. There are also cases--not many in this particular manuscript, but in others--where there are images but they don't have (new) chant information on them; for example, where a really long chant takes up an entire page. e.g. McGill MS73, where folios 19 and 20 continue a chant begun on 18r. Those folios are a gap in the record, but in this case there is in fact chant on them. https://archive.org/details/McGillLibrary-rbsc_ms-medieval-073-18802/page/n39/mode/2up
