### ISSUE TITLE
link to Cantus DB?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#547]
My understanding of the ultimate aim of Cantus Ultimus is that it still works together with some of the information present on the Index/Database, rather than porting all of it; so if I want to see, e.g. concordances, or other chants for the same feast, etc, I would have to head to the appropriate part of the database or Index.
Probably it should be easier for the user to do this. The Cantus ID could link to the appropriate place in the Index (for example) and the chant entry could contain a link to the appropriate place in the Database. That way you don't have to go hunting in the database for information about a chant you just saw in Cantus Ultimus...

**Comment by napulen** [comment]
And in fact, we already have that link in our django model. We just need to make it available in the front end.

Great suggestion, thank you @annamorphism!

**Comment by napulen** [comment]
Marking as `High Priority` because it should only require an `<a>` element somewhere in the frontend templates. (Hopefully!)
