### ISSUE TITLE
Optimize nginx container build

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#552]
We should investigate whether there is a better way to build the nginx container. I suspect that we are not taking as much advantage of docker's caching as we could -- we could have the intermediate images where most of what is installed is installed and any static file changes are closer to the end.

**Comment by napulen** [comment]
Can you provide an example where you think the caching is not being efficient? My experience so far is that when I run `docker compose build` after a change in the source code, I often see only the relevant components being rebuilt.

I would say our most time-consuming containers are the `nginx` one, because of the frontend; and `app`/`celery`. Maybe the latter ones can definitely be optimized in some way.

**Comment by napulen** [comment]
Has this been addressed by #550 or are other changes needed/suggested here?

**Comment by dchiller** [comment]
#550 only dealt with the app container build, but I am thinking it might be some similar reordering as was done there -- I am more familiar with the app container build process, so that's where it stood out to me first. 

Basically, it seems like in the nginx container, we are reinstalling everything even when only the code changes. Maybe this needs to happen, but it seems like it should be that we could keep the cached install, then add the source code, and then do any compiling...but we would have to investigate because I'm not sure off the top of my head what each of the steps in the build is actually doing.

**Comment by napulen** [comment]
Gotcha. Ok, so maybe step forward would be to run a comparison between all recommendations [here](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) and our setup.

**Comment by napulen** [comment]
@dchiller Unless you think this is affecting your development workflow and needs to be fixed, I'd delegate this to future developers.

**Comment by dchiller** [comment]
Yeah, if you look especially at the "Leverage build cache" section, I think that has some implications that we don't quite take advantage of.
