### ISSUE TITLE
Lubiąż, PL-WRu I F 401: Proof folio mapping

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#585]
I think most of this is fine, but a special look should be taken at the end of the manuscript where there are multiple fragment pages of chant that I think are mapped to a single folio (272w)

**Comment by annamorphism** [comment]
Not exactly to do with the folio mapping but:

1. The chants seem to go left to right instead of in two columns, so they read (1st on left page) (1st on right) (2nd on left)(end on right) which is pretty confusing. (1st on left)(2nd on left.)...(1st on right)(2nd on right) seems more desirable. 

2.An added wrinkle is that for whatever reason this MS seems to have nothing in the MS text reading field on the DB. (NO idea why--this is required, but maybe it wasn't when the entries were made?) So the Volpiano shows up with no text.

**Comment by annamorphism** [comment]
272w should be mapped to image 278.  For whatever reason, the chants on image 277/279 don't seem to have Cantus entries; on the one hand, that means we also don't have to worry about mapping multiple images to the same place; on the other hand, it means it's not exactly true to say no chants begin on this page. Maybe this message should really say that no chant *records* begin on this folio...

**Comment by annamorphism** [comment]
also! something really wacky is happening when I try to view the chant records for everything on the right hand page--it keeps opening the record for the lefthand page instead!  So e.g. on 118v/119r, I can see the record for "Quae mulier" and "Estote" (both on 118v) but trying to open "Praeceptor" (which is on 119r) opens "Quae mulier" instead.
![image](https://user-images.githubusercontent.com/67451875/184238059-97d5010b-4917-42b7-9a60-8964c744167e.png)

**Comment by annamorphism** [comment]
anyway the folio mapping *seems* correct (except the last image) but the funny behaviour of the double pages makes it hard to proofread at the moment.

**Comment by dchiller** [comment]
> 1. The chants seem to go left to right instead of in two columns, so they read (1st on left page) (1st on right) (2nd on left)(end on right) which is pretty confusing. (1st on left)(2nd on left.)...(1st on right)(2nd on right) seems more desirable.

Yes, it's very confusing. I actually made an issue for this #584, but makes sense that this is hard to proof-read before that is fixed. So, maybe we can return to this one after that is done :)

**Comment by dchiller** [comment]
> also! something really wacky is happening when I try to view the chant records for everything on the right hand page--it keeps opening the record for the lefthand page instead! So e.g. on 118v/119r, I can see the record for "Quae mulier" and "Estote" (both on 118v) but trying to open "Praeceptor" (which is on 119r) opens "Quae mulier" instead. 

Yes, this is very weird (and bad) -- will take a look -- thank you!

**Comment by dchiller** [comment]
> 272w should be mapped to image 278. For whatever reason, the chants on image 277/279 don't seem to have Cantus entries; on the one hand, that means we also don't have to worry about mapping multiple images to the same place; on the other hand, it means it's not exactly true to say no chants begin on this page. Maybe this message should really say that no chant _records_ begin on this folio...

Fascinating! I wonder why those don't have one...

Yes, it would be very easy to change that default message to "No chant records..." so that it encompasses both where there are no chants *and* where there are chants but no CantusDB records. 

Trying to differentiate those two cases relates to what we were discussing in #589, and is probably a longer-term fix.

**Comment by dchiller** [comment]
Follow-on question: should we alert Cantus DB about this? Or is this probably something that they knew about and made a conscious choice not to record those few folios?

**Comment by dchiller** [comment]
The following problems should be solved by #604 and #605:
1. A new message shows that "No chant records" begin on a folio for which there are not chants given by Cantus DB rather than "No chants"
2. The order of chants shown for an image with two folios per image should now be in the order:
     - Chant 1 on left
     - Chant 2 on left
     - ...
     - Last chant on left
     - Chant 1 on right
     - Chant 2 on right
     - ....
     - Last chant on right
3. The chant that you click on in double-folio images should now be the one that accordions out, because we now reference these objects by item and not by sequence (the problem with referencing by sequence is that there the first chant on both folios in the image were conflicting).

**Comment by dchiller** [comment]
Once these fixes are on prod I will fix the mapping of 272w -- I will alert this thread -- and then this should be ready for another look. Thanks!

**Comment by dchiller** [comment]
This manuscript has now be re-mapped with 272w mapped to image 278.
