### ISSUE TITLE
St. Gallen, CH-SGs 391: Proof folio mapping

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#615]
I think this is mostly good but I'm not sure what's going on with Folio 22b.

I mapped it to the image because the last three chants match, and the top of the page is a continuation of the chant starting on the previous folio, but I can't make heads or tails of what's going on in between.

**Comment by annamorphism** [comment]
@dchiller your intuition was correct! What's going on in between is a lot of shorthand with very few headings to divide things up--basically it's giving the titles of chants to sing on particular processions. (And inspecting it in this way made me realize some edits need to be made in the database...) Mapping is correct for this folio, though. I will check the others.

**Comment by annamorphism** [comment]
otherwise this mapping looks good, closing.
