### ISSUE TITLE
full name of abbreviated fields

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#636]
Sometimes there seems to be an error expanding the field for Office/Mass, as in the example from Dendermonde below.
![image](https://user-images.githubusercontent.com/67451875/194395665-76a61b36-08fa-4d41-9124-cbba2a0fbe5a.png)

Other chants marked X in the DB behave just fine...

**Comment by dchiller** [comment]
For some reason, this seemed to have resulted from an error in the chant import process for this manuscript. I'm not sure why, but re-importing the chants from CantusDB did the trick.

Closing this, as this seems to have been a one-off issue and I can't replicate anything more systematic.
