### ISSUE TITLE
Archive old Cantus Ultimus site at accessible sub-domain

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#649]

**Comment by dchiller** [comment]
The old Cantus Ultimus site is now visible at cantus.archive.simssa.ca. This is server through the staging router, so connection through the McGill VPN and/or at the lab is required.

**Comment by fujinaga** [comment]
Links to manuscripts in https://cantus.archive.simssa.ca/manuscripts/ are not working.

**Comment by annamorphism** [comment]
re-opening since, as Ich already pointed out, the archived links to manuscripts are broken (they redirect to simssa.ca). Or is that by design?

**Comment by dchiller** [comment]
Thanks...those links should definitely be working. I'll take a look.

**Comment by dchiller** [comment]
@fujinaga @annamorphism 

cantus.archive.simssa.ca is now back up and the links to specific manuscripts are working. Search is looking good too. Not sure if you were trying to do something specific when you found this; if you were, give it a try now and let me know if something is still broken.

**Comment by dchiller** [comment]
The archive site does not seem to be serving images right now.

**Comment by annamorphism** [comment]
...I can't even get the archive site to load? Gives me a server timeout.

**Comment by dchiller** [comment]
Are you on the McGill VPN? The archive site is like staging and so will only be accessible from the McGill network, and it is working fine for me rn.

**Comment by annamorphism** [comment]
ah, that would do it. Yes, I can get in on the VPN (though my browser complains about the certificate setting). The images are giving Invalid objectData setting Error Code 0, which I assume is the problem you were having.

**Comment by dchiller** [comment]
> The images are giving Invalid objectData setting Error Code 0, which I assume is the problem you were having.

Yeah, that's what I'm getting -- so that's a (hopefully the) remaining problem to solve here.

**Comment by dchiller** [comment]
The reason we are getting this error is because the browser is blocking mixed content. The `cantus.archive.simssa.ca/manuscript/[manuscript_id]` page is served securely with https (even though the certificate is currently invalid -- this issue has been raised in the operations repository) but the call to the manifest proxy is not secure (`http://cantus.archive.simssa.ca`).

**Comment by dchiller** [comment]
Ok, in getting back around to this (and #748), I determined the cause, and it's one of the dumbest possible ones. The old version of django we were using was redirecting the manifest-proxy call to http from https because the manifest urls did not have a trailing slash. So adding a trailing slash to the urls in the database meant that this redirect didn't happen, the manifest proxy call is over https, and so there is no more mixed content and no more browser complaints.
