### ISSUE TITLE
Fix odd search modal windowing

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#677]
Ich found the following odd windowing in some searching on staging:

![image](https://user-images.githubusercontent.com/11023634/216852419-f897a25f-f94d-427c-a3fd-a618740d3362.png)

I can't currently seem to replicate, but am asking for some additional details in hopes that that helps me narrow it down.

**Comment by annamorphism** [comment]
I'm also using Monterey (like @fujinaga) , and I can't seem to replicate this in any browser. Mysterious.

**Comment by dchiller** [comment]
For some reason, many more divs on staging have a class with attribute `overflow: scroll` than on production. On production, this is only set for the one div where it is actually needed (the `diva-viewport`, or the `result-table-wrapper` in the case of search results), but on staging many ancestor divs have the same. 

I'm not sure yet what was changed that made this the case...
