### ISSUE TITLE
`Feast` and `Genre` search suggesters fail on certain strings

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#716]
I'm not sure why this is happening and it only seems to occur on a few strings.

I currently have 

Einsiedeln, CH-E 611                                                                                                                                       
Salzinnes, CDN-Hsmu M2149.L4                                                                                                                                          
Tours, F-TOm 149

loaded. 

In `feast` search, `a` gives 10597 results, `ag` and `age` give 0 results (but with no message and with headers that make it look like there should be results), and `ager` gives 0 results (with the appropriate message). Same thing in `genre` search.

The traceback in those weird middle situations is
![image](https://github.com/DDMAL/cantus/assets/11023634/6e12b53d-91a0-4b02-ad37-8d76150ed405)
or similar.

**Comment by ahankinson** [comment]
Your Solr log file will tell you what exactly failed. I would `tail` the log file and then trigger the error.
