### ISSUE TITLE
Back button does not work

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/cantus#72]
To reproduce:

 -- Go to the list of MSS
 -- Select a MSS
 -- Click Back

The back button will simply refresh the MSS page, not take you to the list of MSS.

**Comment by wabain** [comment]
What should happen in the following case?

1. Go to the list of MSS
2. Click a MS
3. Scroll down to the second folio
4. Click back

Should this (A) make it jump to the first folio or should it (B) take you back to the list of MSS? We've been working on this bug on the basis that the correct behavior would be A (and I think I have a patch that does it now) but B would be trivial to implement and I think it might actually be the right answer.

**Comment by wabain** [comment]
Putting that in a more straightforward way: should scrolling through the folios *ever* push a new state to history? Because if not then this is pretty easy to solve.
