### ISSUE TITLE
Salzinnes duplications

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#722]
When searching either of the two Salzinnes manuscripts, the results show up duplicated. This doesn't happen on other manuscripts, so it probably has to do with the existence of two images associated with the same Cantus data.
It seems like one result is the one for /25 and one is for /209, even though you are nominally searching only one or the other. In the screenshot below you can see that both the Montreal and Leuven results are attached to the search of the Leuven MS. 
<img width="1238" alt="image" src="https://github.com/DDMAL/cantus/assets/67451875/910f886c-9c28-455d-b494-cc8d2b10f24d">

**Comment by dchiller** [comment]
Reason is that when we search in the Manuscript Detail view, we pass a query parameter for the `siglum` field. In this case, we have two manuscripts with the `CDN-Hsmu M2149.L4` siglum (because of the two sets of images) and so both are returned.
