### ISSUE TITLE
"search text" only searches MS spelling?

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#751]
Searching "sepulchrum" gets you no hits: 
<img width="563" alt="image" src="https://github.com/DDMAL/cantus/assets/67451875/c93e5e51-8cf4-4d37-858d-f2fa5c385985">
Instead you have to search "sepulcrum" (the "MS spelling") to find relevant chants. 
 <img width="578" alt="image" src="https://github.com/DDMAL/cantus/assets/67451875/40b8aee2-f010-47e4-9d5a-741f8da6d89b">

This is a little weird, since the spelling given in the transcription is actually the "standardized spelling", so you woudl sort of think it would show up as a result...
<img width="536" alt="image" src="https://github.com/DDMAL/cantus/assets/67451875/fbdb493e-b830-48b8-a817-73a95670df90">

**Comment by dchiller** [comment]
I think it is the other way around? In this chant "sepulchrum" is in the MS spelling and "sepulcrum" is in the standardized spelling: http://206.12.88.113/chant/614855

Regardless though, I agree we should return matches from either standardized or MS spelling. This should be an easy fix.

**Comment by annamorphism** [comment]
right you are!
