### ISSUE TITLE
Update all CantusDB links to cantusdatabase.org (NewCantus)

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#761]
Links need to be updated in both the Cantus Ultimus code and in the static pages.

Resolution depends on the results of https://github.com/DDMAL/CantusDB/issues/967 because we use `/genre` in CU code.

**Comment by jacobdgm** [comment]
I'm setting up redirects from /genre to /genres and from /office to /offices presently; use the plural version!
