### ISSUE TITLE
GB-Ob Can. Lit. 202: Proof folio mapping

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#782]
`GB-Ob Can. Lit. 202` is now available and mapped on [Cantus Ultimus](https://cantus.simssa.ca/manuscript/123687/). I have done a preliminary check of the mapping, and all looks good. 

@annamorphism Opening this issue to request your review of the mapping. 

@jacobdgm @lucasmarchd01 You should now be able to link to these images from CantusDB. I have updated the manuscript-level link in CantusDB to point to Cantus Ultimus.

**Comment by annamorphism** [comment]
@dchiller on initial perusal it looks pretty good to me too!

**Comment by jacobdgm** [comment]
> @jacobdgm @lucasmarchd01 You should now be able to link to these images from CantusDB. I have updated the manuscript-level link in CantusDB to point to Cantus Ultimus.

Is there immediate action required on our part for this? I can get to work on a tool to take a CSV file and update image links based on it - since you already have a mapping set up, would you be able to export such a CSV for an initial test for this?

I'm imagining something structured like this
```
source,folio,image_link
123456,001r,http://cantus-ultimus.ca/some-path?some=parameters
etc.
```

**Comment by dchiller** [comment]
> Is there immediate action required on our part for this?

Nothing urgent. I think the next step here really is https://github.com/DDMAL/CantusDB/issues/940.



> since you already have a mapping set up, would you be able to export such a CSV for an initial test for this

Sure thing....for testing and even for the other manuscripts this will be useful.

**Comment by dchiller** [comment]
@jacobdgm @lucasmarchd01 I've attached here a test csv file for your use. #784 is also now open which will allow you to access these csv's for any manuscript on Cantus Ultimus going forward.
[salzinnes_folio_mapping_export-test.csv](https://github.com/DDMAL/cantus/files/12619044/salzinnes_folio_mapping_export-test.csv)

**Comment by dchiller** [comment]
Whelp! Got so down the rabbit hole of providing a csv export that I forgot about the contents. The image links you want here are to Cantus Ultimus, not to the original IIIF viewer...I'll get that fixed.

**Comment by dchiller** [comment]
Closing. This source is being unpublished because it does not have full texts.
