### ISSUE TITLE
Add support for IIIF requiredStatement on Cantus Ultimus

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#786]
From @ahankinson in a discussion at [CantusDB#1072](https://github.com/DDMAL/CantusDB/issues/1072#issuecomment-1735894403):

> The IIIF manifests usually have a requiredStatement that are required, by the spec, to be shown by viewers. This usually specifies the institution that provides the images.
> 
> There is also a provider section that can give more information about the source of the manifest.
> 
> https://iiif.io/api/presentation/3.0/#requiredstatement
> 
> IIIF v2 had attribution and logo sections.

We need to  add support for these required statements so Cantus Ultimus is in compliance with IIIF standards.

**Comment by annamorphism** [comment]
to be clear, does adding the requiredStatement in CU mean we no longer need to worry about whether CantusDB links to CU or to the original archive? or is it sort of a both/and situation?

**Comment by dchiller** [comment]
Both/and...

We need to add the requiredStatement because it turns out that IIIF viewers need to do that to be considered "up to code". And because it would generally good to provide credit where credit is due on images we are showing on Cantus Ultimus. 

It seems to me based on the discussion in DDMAL/CantusDB#1072 that we still don't have a settled decision on when CantusDB links to where.

**Comment by annamorphism** [comment]
Ok, sounds like a discussion is in order then!

**Comment by dchiller** [comment]
Note: In the Presentation API v 2, the equivalent seems to be the `attribution` attribute.
