### ISSUE TITLE
Remove dependence on CAO concordances

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#797]
References to CAO Concordances were removed in Cantus DB with https://github.com/DDMAL/CantusDB/pull/431.

Now that we are using New Cantus, we need to update our code to the same.

**Comment by dchiller** [comment]
@jacobdgm @annamorphism @lucasmarchd01 

Is your impression that these are not coming back?

**Comment by annamorphism** [comment]
The information is on Cantus Index but not CantusDB, and my impression is that this division is indeed likely to stay that way--if CU were to reference the CAO concordances it should be taken from there and not from Cantus Database.

**Comment by dchiller** [comment]
Do you think we want CU to have this information? I am imagining we were importing it previously because it was in CantusDB and not because we had any particular need for it in CU -- it's certainly not used anywhere currently.

**Comment by annamorphism** [comment]
Good point. I think it would be interesting to have some easy way of accessing concordances (of either the CDB or CAO variety), if it is indeed to be the Ultimate Cantus, but that definitely falls under "future features to discuss" and not something that needs to happen now.

**Comment by dchiller** [comment]
Ok, since this is a future thing, and since even if we do end up importing them the way we would import them would have to change given that they'd come from CI rather than CDB, I will remove the code that handles them
