### ISSUE TITLE
Provide field search for differentia data

### ISSUE THREAD

**Issue by dchiller** [DDMAL/cantus#804]
The differentia field is currently indexed, but we provide no search interface. A new search field should be added that allows users to search both the `differentia` and `differentiae_database` fields (#805 involves adding that field).

Tagging @annamorphism for updates.

**Comment by dchiller** [comment]
@annamorphism I would love your thoughts on this:

I know we want to search both `differentia` and `differentiae_database` fields in the `All Text Fields` search.

For the field specific search, do we want separate searches for `differentia` and `differentiae_database`? Or search both in a single "Differentia" field search? If we offer separate searches, I think we'll need to provide some information on what the differences are...

**Comment by annamorphism** [comment]
This is an interesting question! From a practical perspective, they probably could be lumped together for most search purposes: the differentia_database values are usually number+letter, e.g. "133a", which is not (I think) a form "differentia" values take, so there wouldn't be confusion in the searches. 
That said, they *are* different things (some chants may have both), and useful for slightly different things: "differentia_database" is probably more useful across manuscripts, but "differentia"is probably more useful within a single MS. So probably separate searches is better.
I could probably come up with some way of summarizing each in a sentence or two, so they can be analogous to the two Volpiano searches.

**Comment by dchiller** [comment]
Perfect! Let's plan on different fields then. We could do something similar to the "About Volpiano" pop-up if we wanted to to explain the difference.
