### ISSUE TITLE
Cantus ID search or link

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/cantus#816]
All chants in Cantus Ultimus display their Cantus IDs. However, you can't search for a Cantus ID, nor does the ID link to Cantus Index the way it does on Cantus DB. This means if you want to know whether there are other examples of some particular chant on Cantus Ultimus, you have to go out to CDB (where the concordances also don't display currently), hop from there to Cantus Index, and  pop open the concordances list there--but then you still don't know which of those are viewable back on CU. Or you could search CU for the text of some chant, go to the result, and see if the ID is or is not matching the target search. 
This seems a bit cumbersome. 
Possible solutions:
-be able to search for Cantus IDs (cons: one more field to search; otherwise probably the best solution?)
-Not search for IDs, but have them displayed so you can see which results are under the same ID (drawback: potentially confusing to have IDs showing up with little explanation)
-Have the numbers in each chant field link to CI (drawback: still doesn't tell you what else _on CU_ might be the same chant, but maybe useful interlinking anyway).

**Comment by dchiller** [comment]
> -be able to search for Cantus IDs (cons: one more field to search; otherwise probably the best solution?)

I think I agree that this is the best. I don't think from a technical standpoint it matters that there is one more field to search, but it may get cumbersome for the user to have a big long drop-down of search fields. I feel like that is really an interface problem, given that something like a Cantus ID search seems like a very reasonable and useful thing to be able to do.

**Comment by annamorphism** [comment]
> Does this mean just have the Cantus ID shown on the little chant panel when you click on a chant to accordion it open?

The Cantus ID is already there--I meant in the search results window, which tells you MS, folio, incipit,  feast/office/genre/mode, but not the Cantus ID. But it's sort of a lot of columns already, so maybe it's not necessary to have every single bit of metadata displayed here. (See also: differentia, which are also not shown here.)

**Comment by dchiller** [comment]
well, I was just running into this with respect to differentia. I really don't think it's good that you can search for something and then can't see what got found. Especially with all-text search. So this seems like it would be good regardless.

**Comment by annamorphism** [comment]
> well, I was just running into this with respect to differentia. I really don't think it's good that you can search for something and then can't see what got found. 

This is a very compelling point!
